opendatateam/udata-front-kit

config.yaml, package-lock.json, package.json, src/components/Card.vue, src/main.js, src/services/api/DatagouvfrAPI.js, src/services/api/resources/OrganizationsAPI.js, src/store/index.js, src/views/organizations/OrganizationDetailView.vue, src/views/organizations/OrganizationsListView.vue
Due to the new config file #9, it became necessary to paginate organizations and datasets.
This PR also introduces a clean(ish) organizations list page with custom cards (vue-dsfr ones too limited) and a (dumb) loading state overlay since we're now making a lot more requests.
=> Paginate datasets and organizations

src/services/api/resources/DatasetsAPI.js, src/services/api/resources/OrganizationsAPI.js, src/store/DatasetStore.js, src/views/organizations/OrganizationDetailView.vue
Use another endpoint to fetch an organization's datasets which does not include archived datasets.
We need the organization technical id for this endpoint, so the fetch logic is a bit more convoluted.
=> Filter archived datasets

src/services/api/SearchAPI.js, src/store/SearchStore.js, src/views/datasets/DatasetsListView.vue
Adds pagination and organization facet to search page.
Needs https://github.com/ecolabdata/ecospheres-search-index/pull/2, which also implements a default sort.
I used a select for the organization facet, which is not optimal but there's no autocomplete component (for example) in DSFR.
=> Search improvements

config.yaml, src/App.vue, src/composables/fetch.js, src/icons.js, src/main.js, src/router/index.js, src/services/AuthService.js, src/services/api/DatagouvfrAPI.js, src/services/api/OauthAPI.js, src/services/api/resources/ReusesAPI.js, src/services/api/resources/UserAPI.js, src/store/UserStore.js, src/views/LoginView.vue, src/views/LogoutView.vue
This adds support for oauth connection on data.gouv.fr. You can login, logout and there's a crude detection for a bad token (expired) that will redirect you to the login flow. The header is responsive to your login state.
This also switches to demo.data.gouv.fr as a backend. https://github.com/ecolabdata/ecospheres-search-index will adapt to the config file when it's merged on main, but we'll need to reset the index in order not to mix prod and demo datasets.
NB: this won't work as a PR preview, the callback URL for oauth won't match. It works on local if you use the default port (5173).
=> Basic support for data.gouv.fr oauth

src/components/Tile.vue, src/store/BouquetStore.js, src/views/bouquets/BouquetDetailView.vue, src/views/bouquets/BouquetEditView.vue
A user description can be filled when adding a dataset to a bouquet. It can be edited later. It's also displayed on the bouquet detail view for each dataset.
NB: storage is done "flat" in the `extras`, using a specially formatted key for each dataset. It could be done via a nested list attribute `ecospheres: []` but it made the code more complex so I kept with flat.
=> User description when adding a dataset to a bouquet

README.md, config.yaml, package-lock.json, package.json, src/services/api/SearchAPI.js, src/store/BouquetStore.js, src/store/SearchStore.js, src/views/bouquets/BouquetDetailView.vue, src/views/bouquets/BouquetEditView.vue, src/views/datasets/DatasetsListView.vue
This switches to the data.gouv.fr's datasets search by topic. The topic is defined as `universe_topic_id`, ATM as a slug but very soon as a technical id (pending data.gouv.fr's deploy).
It removes the organization filter since faceting is not available anymore. We could build it again from the organizations list, but it's another story for another time :-)
This also introduces a `universe_name` variable used to tag bouquets and namespace bouquets extras, for the sake of a generic solution.
=> Switch to data.gouv.fr search API by topic

configs/ecospheres/config.yaml, package.json, src/assets/main.css, src/components/Tooltip.vue, src/views/bouquets/BouquetDetailView.vue, src/views/bouquets/BouquetEditView.vue
Close #87
Close #160
Fix #148
Fix #158
> Utilisateur: agent / producteur de données
>
> Quand je veux partager les données nécessaires pour réaliser des indicateurs,
> Je veux pouvoir maintenir un même catalogue au même endroit,
> Pour que d'autres puissent s'en servir et l'améliorer.
Avec le composant dsfrAccordion il n'y a pas la possibilité de mettre le tag "donnée non disponible" ou "donnée non manquante" à proximité du titre.
J'ai placé le tag "donnée non disponible" ou "donnée non manquante" au dessus de la description de la donnée. Il est visible au déroulement de l'accordéon.
Je remplis "Objectif du bouquet",
Je clique sur "Enregistrer" (un bouton bleu),
Je suis redirigé vers le bouquet que je viens de créer,
Je peux lire un message de succès qui m'indique que tout s'est déroulé …
=> feat(bouquet): crée bouquet avec donnée non-disponible/manquante

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, configs/sante-publique-france/config.yaml, src/services/api/DatagouvfrAPI.js, src/services/api/__tests__/DatagouvfrAPI.test.js, src/services/api/resources/TopicsAPI.js, src/store/DatasetStore.js, src/store/OrganizationStore.js, src/store/TopicStore.js, src/views/bouquets/BouquetDetailView.vue, src/views/datasets/DatasetDetailView.vue
This introduces usage of data.gouv.fr's API v2, [especially the new topic's one](https://github.com/opendatateam/udata/pull/2913).
- Fetch topic list via APIv2 and use the `tag` filter
- Deal with new response format from v2
- Datasets from Topic need to be fetched via HATEOAS
- Resources from Dataset need to be fetched via HATEOAS
This is the minimum viable implementation I can think of. We could migrate more stuff to v2, especially datasets, but ATM we use it only when we need and use both v1 and v2.
I did not look into Topic write operations since they're not available on frontend anymore (when I started this morning, might have changed since then).
~~NB: [`npm run format`](https://github.com/ecolabdata/ecospheres-front/pull/154/commits/a1d11498e1b37c636018e1b38a45e6e44b9077b0) makes a …
=> Topic api v2

src/views/bouquets/BouquetEditView.vue
Feature proposal Recap page
Fix #151 
After filling in the bouquet creation information in steps 1, 2 and 3, I can view the pre-filled information, validate it or modify it if necessary by returning to the previous steps by clicking on the pencil icons.
- Useless code was appearing on step3, I removed it
- Keep accordion open
=> Recap page after creating bouquet from step 1 to 3

.vscode/extensions.json, package-lock.json, package.json, tsconfig.dev.json, tsconfig.json, vite.config.ts
Closes #175
TypeScript devrait marcher sur [VSCode](https://code.visualstudio.com/).
Ce n'est pas le cas: 
Via @abulte 
- Intègre le config `vite` et `.vscode`
- 🛠 Inclut `include` dans `tsconfig.json` et `tsconfig.dev.json` (les configs `path` ne sont pas héritables)
- 🛠 Inclut les config `volar` et `typescript` dans `.vscode`
=> build: fix typescript in vscode

.github/workflows/node.js.yml, package.json, src/views/bouquets/BouquetEditView.vue
Relates to #191
Lorsque je commit,
je m'attends à ce que le pre-commit hook applique `npm run format`.
Ce n'est pas le cas, cf. #191
Quand je commit, tout es bien formatté.
- 🛠 Ajoute la racine (`.`) dans `lint-staged`.
=> build(npm): fix husky et applique format

configs/ecospheres/config.yaml, src/views/bouquets/BouquetDetailView.vue
Close #112 
Visualisation de la page du bouquet
Après avoir rempli le formulaire de création de bouquet ou après avoir chercher un bouquet, j'accède à la page du bouquet avec les informations liés: thème, chantier, titre, description, jeux de données(si existant et trouvé)
Il y a la possibilité de créer un nouveau bouquet ou de copier l'url de la page
=> feat(bouquet): visualisation d'un bouquet

CONTRIBUTING.md, docs/architecture-decisions/1-change-schema-pour-trame-de-bouquet.md, docs/requests-for-comments/1-changer-le-nom-schema-de-bouquet.md
Closes #201 
✅ Acceptée ([RFC #1](https://github.com/ecolabdata/ecospheres-front/blob/4f152d19afd0fdffcfa9c8a3c8a2f66779cd9642/docs/requests-for-comments/1-changer-le-nom-schema-de-bouquet.md))
Le périmètre d'Écosphères comprend la notion de « schéma de bouquet ». Le terme
s'est avéré confus. Une discussion a eu lieu pour en trouver un meilleur terme.
Utiliser le terme « trame de bouquet » à la place.
- Mettre à jour les issues Github
- Mettre à jour d'autres supports de communication
=> ADR: change schéma pour trame de bouquet

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/App.vue, src/views/AboutView.vue, src/views/HomeView.vue, src/views/LoginView.vue, src/views/LogoutView.vue, src/views/SimplePageView.vue, src/views/bouquets/BouquetDetailView.vue, src/views/bouquets/BouquetEditView.vue, src/views/bouquets/BouquetsListView.vue, src/views/datasets/DatasetDetailView.vue, src/views/datasets/DatasetsListView.vue, src/views/organizations/OrganizationDetailView.vue, src/views/organizations/OrganizationsListView.vue
- colored banner in homepage. 
- parametrize colors for each configs
or
=> feat: colored banner in homepage

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/views/HomeView.vue
! important : need to merge #184 first because it is based on `feat/colored-banner`
- parametrize a secondary search in homepage (useful for meteo.data.gouv.fr use case where they need a guided search)
=> feat: allow secondary search rerouting to another page

configs/ecospheres/config.yaml
Rebranding Ecosphères -> ecologie.data.gouv.fr.
Les textes sont tirés du [figma](https://www.figma.com/file/LXSt7OH4jGh6yJcc8Dsk6O/%F0%9F%86%95-Verticales-data.gouv.fr?type=design&node-id=108-1571&mode=design&t=StsNxyKucIokc9dW-0).
=> Rebranding ecologie.data.gouv.fr

src/components/HomeTopics.vue, src/views/HomeView.vue
Modification du style de la search bar pour passer de ce style : 
A celui-là :
=> style: style for search bar

src/views/HomeView.vue
Closes https://github.com/etalab/data.gouv.fr/issues/1231
- 🤟 Utilisation de la font Spectral en italique pour le sous-titre
- 🛠 Refonte des styles du titre et du sous-titre pour utiliser les classes du DSFR et les utilitaires de data.gouv.fr-components
- 🛠 Correction de l'affichage de la search-bar sur les écrans entre 1180px et 1248px.
=> Use spectral for subtitle

configs/ecospheres/config.yaml
Modifications dans les onglets du menu sur ecologie.dgfr : 
- Renommage "Jeux de données" en "Données"
- Suppression de "Organization" (cassé de toutes façons)
=> Modifications menu ecologie.dgfr

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, configs/sante-publique-france/config.yaml, src/components/Navigation.vue, src/services/routerUtils.js, src/views/bouquets/BouquetEditView.vue
Nom de variable plus parlant pour `router_items`, cf https://github.com/ecolabdata/ecospheres-front/pull/259#discussion_r1424117260
=> refacto: rename menu_items to router_items

configs/ecospheres/config.yaml, src/services/api/resources/DatasetsAPI.js, src/store/DatasetStore.js
Fix la page détail d'une organisation en utilisant le bon endpoint sur l'API v2. Réintroduit le routage vers une page organisation sur ecospheres, mais sans l'afficher dans le menu.
Related #238 
Related #211
=> fix(org): fix org detail page

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/components/DiscussionsList.vue, src/model/discussion.ts, src/services/api/resources/DiscussionsAPI.ts, src/store/DiscussionStore.ts, src/store/UserStore.js, src/views/bouquets/BouquetDetailView.vue, src/views/datasets/DatasetDetailView.vue
Permet la création de discussions et de réponse aux discussions dans le composant `DiscussionsList`. 
Activable via le feature flag `website.discussions.(topic|dataset).create`.
Limitations connues : 
- ~~le statut connecté est attendu comme pré-requis, pas de redirection vers l'authentification car elle est aujourd'hui hijackée par les bouquets (autre PR je pense)~~
- la redirection vers le login ne ramène pas à l'endroit exact de l'action
- bug (?) sur data.gouv.fr qui empêche la création de plusieurs commentaires à moins de ~10 sec d'intervalle (mais le cas est géré, on peut réessayer)
=> feat(discussions): allow discussion and comment creation

src/components/Navigation.vue, src/services/routerUtils.js
Fix #236
Un peu compliqué à cause de deux choses :
- il faut réécrire les routes pour que vue-router considère `/xxx/yyy` comme enfant de `/xxx` et donc réputée active  https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes
- [le DSFR se base sur `aria-current`](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale) pour appliquer le style, et ce style est difficile à répliquer pour l'appliquer à la classe `router-link-active` qui est posée par `vue-router` grâce à supra. On manipule donc l'attribut `aria-current` en utilisant le matching des liens de `vue-router` avant d'injecter l'item de navigation au menu DSFR.
=> fix: highlight du menu sur une page enfant

src/App.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/model/index.ts, src/store/TopicStore.ts, src/store/UserStore.ts, src/utils/index.js
Fix #307 
Le fix est là https://github.com/opendatateam/udata-front-kit/pull/311/commits/471d72ad792a86c7b086d14672c5ba1db28c8a26.
Le reste consiste à refactorer le composant en TS, et les stores associés, pour que le linting ait pu permettre de détecter cette erreur (`description` n'est pas dans le type `DatasetProperties`) https://github.com/opendatateam/udata-front-kit/pull/311/commits/4daef4efd27fc9c285c28638a54e67d26f4e4014.
Le refactor aggrave la dépendance Bouquet/Ecosphères soulevée dans #294 pour scoper un peu cette PR et ne pas partir dans un refacto des types ou de la gestion des univers. La vue est de toute façon dans `custom`.
Related #309 (getting there, page after page)
=> fix: refactor: BouquetDetailView dataset description

src/custom/ecospheres/components/BouquetDatasetAvailability.vue, src/custom/ecospheres/components/BouquetDatasetList.vue, src/custom/ecospheres/components/forms/bouquet/BouquetContentFieldGroup.vue, src/custom/ecospheres/components/forms/bouquet/BouquetPropertiesFieldGroup.vue, src/custom/ecospheres/components/forms/bouquet/BouquetThemeFieldGroup.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/custom/ecospheres/views/bouquets/BouquetEditView.vue, src/store/TopicStore.ts
Fix #306 
Based on #311 
Related #309 
Corrige trois anomalies :
- Markdown non interprété pour la description d'un jeu de données dans la liste d'édition d'un bouquet #306 
- Le tag `Availability` n'était pas traduit dans la même vue, création d'un composant pour l'afficher comme dans `BouquetDetailView`
- Le sujet d'un bouquet n'était pas indiqué comme obligatoire (*)
Dans la même veine que #311, cette PR corrige le linting/typing des composants impactés par le parcours. Les commits sont atomiques et indique s'il s'agit d'un fix ou d'un refactor.
=> fix: refactor: BouquetEditView markdown desc and availability 

src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/components/BouquetSearch.vue, src/custom/ecospheres/components/forms/bouquet/BouquetFormRecap.vue
Related #309 
Based on #312 
Corrige le linting et le typing sur `BouquetFormRecap`, `BouquetSearch`, `BouquetList` (linting OK sur `Bouquet*`).
=> refactor: BouquetFormRecap, BouquetSearch, BouquetList

src/assets/main.css, src/components/HomeThemes.vue, src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/views/bouquets/BouquetsListView.vue
Fix #274 
Fix #316 
Related #178 
- Corrige le breadcrumb sur la page bouquets
- Ajoute un titre "Bouquets" pour être cohérent avec les autres pages
- Corrige le style pour être cohérent avec les autres pages (espacement)
- Refactor deux composants en composition API #178 
- Nettoie un peu `HomeThemes` par opportunisme
=> fix: refactor: bouquets breadcrumb

configs/ecospheres/config.yaml, src/custom/ecospheres/components/forms/bouquet/BouquetContentFieldGroup.vue, src/custom/ecospheres/components/forms/bouquet/BouquetPropertiesFieldGroup.vue, src/custom/ecospheres/components/forms/bouquet/BouquetThemeFieldGroup.vue, src/custom/ecospheres/views/bouquets/BouquetAddView.vue, src/custom/ecospheres/views/bouquets/BouquetEditView.vue, src/model/index.ts, src/services/routerUtils.js, src/store/TopicStore.ts
Fix #280 
Related #225 
Related #178 
- Crée un bouquet avec `private: true` jusqu'à la dernière étape (Résumé -> Publier -> `private: false`), aka mode brouillon
- Filtre la liste principale des bouquets en masquant les bouquets en mode brouillon (la vue d'affichage n'est pas compatible avec un bouquet incomplet)
- Ajoute une vue `BouquetAddView` pour la création du bouquet (étape 1), qui redirige ensuite vers l'édition du bouquet pour les étapes suivantes, via une URL de la forme `/admin/bouquets/edit/{id-tech-du-bouquet}`
- La vue `BouquetEditView` tente d'afficher la bonne étape en fonction de la complétion du bouquet, il est ainsi possible de reprendre l'édition en revenant sur l'URL
- La dernière étape publie le bouquet (private: false)
- Il est possible de naviguer entre les …
=> feat: bouquet en mode brouillon (private)

src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix #225 
Fix #318 (opportunisme)
Utilise #321 pour proposer l'édition d'un bouquet (si on en est propriétaire ou admin) depuis l'interface de visualisation d'un bouquet.
La navigation via "Suivant" dans les différentes étapes de création d'un bouquet remet le bouquet en mode brouillon, jusqu'à ce que qu'on revienne à "Publier". A voir si ce comportement est souhaitable.
=> feat: bouquet edit

package-lock.json, package.json
- Corrige une vulnérabilité en upgradant `vite` https://github.com/opendatateam/udata-front-kit/security/dependabot/3
- Corrige le warning suivant (en local) en upgradant `@vite/plugin-vue`, qui est [responsable de l'injection de ces variables](https://vuejs.org/api/compile-time-flags#vite)
> Feature flag __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ is not explicitly defined. You are running the esm-bundler build of Vue, which expects these compile-time feature flags to be globally injected via the bundler config in order to get better tree-shaking in the production bundle.
=> Upgrade vite and @vitejs/plugin-vue

src/components/Tooltip.vue, src/custom/ecospheres/components/forms/dataset/DatasetPropertiesForm.vue
Fix #285 
- désactive "Ajouter le jeu de données" tant que `title` et `purpose` sont vides
- enlève l'astérisque derrière "Utilisez du markdown"
- ajoute une astérisque derrière "Libellé de la donnée"
=> fix(bouquets): handle required fields on DatasetPropertiesForm

src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix #336 
Ferme l'accordéon par défaut sur la vue de détail d'un bouquet.
J'ai repris le comportement de la dernière étape de la création/édition de bouquet : on peut ouvrir en même temps plusieurs éléments de l'accordéon. Ce n'est pas le comportement standard d'un accordéon, cf [exemple du DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/accordeon/). J'ai choisi de rester cohérent avec l'existant, mais la question mérite d'être posée. @martyKN
=> feat(bouquet): collapse accordion on BouquetDetailView

src/router/index.js
On scrolle désormais par défaut vers le haut de la page au changement de page, sauf dans le cas où on utilise les fonctions back ou forward du navigateur.
Fix #319 
Cf https://router.vuejs.org/guide/advanced/scroll-behavior
=> fix(router): scroll to top by default on page change

src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/custom/ecospheres/views/bouquets/BouquetEditView.vue, src/model/index.ts, src/store/TopicStore.ts, src/store/UserStore.ts
Permet la suppression d'un bouquet pour un propriétaire ou un admin (depuis l'interface d'édition).
La logique de vérification des permissions est centralisée dans le UserStore, afin de faciliter une gestion de droits plus complexe.
=> feat(bouquet): allow delete

src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/components/BouquetSearch.vue, src/store/TopicStore.ts, src/store/UserStore.ts
Related #344 
Permet aux utilisateurs connectés d'afficher _leurs_ brouillons.
La dépendance `TopicStore -> UserStore -> user.roles` est maintenant plus propre.
Fix https://github.com/ecolabdata/ecospheres/issues/88
Fix https://github.com/ecolabdata/ecospheres/issues/98
=> feat(bouquet): show user's owned drafts

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/model/api.ts, src/services/api/DatagouvfrAPI.ts, src/store/OrganizationStore.js, src/store/SearchStore.js, src/views/datasets/DatasetsListView.vue
Ajoute la possibilité de filtrer par organisation sur la page jeux de données. 
- La liste des organisations provient du fichier de configuration (et triée dans cet ordre)
- La fonctionnalité est derrière un feature flag dans la conf.
- Le layout est cohérent avec le filtre par topic de meteo.data.gouv.fr.
- Des organisations en 404 ont été supprimées du fichier de configuration
Fix https://github.com/ecolabdata/ecospheres/issues/104
=> feat(dataset): filter by organization

src/components/DiscussionsList.vue, src/main.js, src/services/LocalStorageService.ts, src/store/UserStore.ts, src/views/LoginView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/117
- Dans le flow d'authentification, stocke la route complète en localStorage plutôt que seulement le chemin, notamment pour préserver la query
- Réordonne les imports chaotiques de main.js
- Introduit un service pour la gestion du localStorage
=> fix(auth): store last route instead of last path

src/custom/ecospheres/components/BouquetSearch.vue, src/views/LogoutView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/120
- Force un rafraîchissement de la page au logout, afin d'être sûr de réinitialiser le state (inc. les brouillons)
- Cache le toggle "Afficher les brouillons" pour un utilisateur non connecté (inutile)
=> fix(bouquet): logout cache and anon draft button

src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/utils/avatar.ts
Fix https://github.com/ecolabdata/ecospheres/issues/91
Affiche le propriétaire du bouquet et sa date de création, de la même manière que pour un jeu de données
- Toute la partie haute de la page a été retravaillée pour coller au gabarit de la page jeu de données (et ainsi converger vers data.gouv.fr) et profiter de certaines améliorations (e.g. "Voir plus")
- Le bouton "Editer le bouquet" prend naturellement le style data.gouv.fr (bords arrondis)
- L'organisation s'affichera si le bouquet y est rattaché (future proofing)
- Le bas de la page n'a pas été retravaillé à date (TODO : onglets ?)
- Fun fact : on n'a pas de date de dernière modification sur un Topic, donc je n'affiche que la date de création. Je propose de le rajouter côté data.gouv.fr plutôt qu'en extra : investissement initial …
=> feat(bouquet): show owner and date

configs/ecospheres/config.yaml
part 1/2 of https://github.com/ecolabdata/ecospheres/issues/116
La liste d'orgas est générée à partir de la config suivante : 
```
organizations:
queries: # api/1/organizations/?q=$query
- ddt
- deal
- direction+departementale+territoire
- direction+regionale+environnement
- dreal
slugs:
- ademe
- agence-nationale-de-la-cohesion-des-territoires
- agence-nationale-de-lhabitat
- agence-ore-3
- agence-regionale-de-la-biodiversite-nouvelle-aquitaine-1
- centre-scientifique-et-technique-du-batiment
- gip-bretagne-environnement
- grand-lyon
- institut-francais-de-recherche-pour-lexploitation-de-la-mer
- institut-national-de-l-information-geographique-et-forestiere
- institut-national-de-la-statistique-et-des-etudes-economiques-insee
- meteo-france
- …
```
=> Update orgas univers Ecosphères

.vscode/extensions.json
Deprecated extension, Volar is enough now.
=> chore: remove vscode reco ts-vue-plugin

package-lock.json, package.json, src/custom/ecospheres/components/BouquetDatasetList.vue, src/icons.js
Fix https://github.com/ecolabdata/ecospheres/issues/93
Permet de réordonner les jeux de données dans un bouquet (via l'interface d'édition de ce step).
⚠️ L'orde est sauvegardé après avoir cliqué sur suivant (cohérent avec le reste de l'édition).
=> feat(bouquet): reorder datasets

src/custom/ecospheres/components/BouquetDatasetAccordionTitle.vue, src/custom/ecospheres/components/BouquetDatasetAvailability.vue, src/custom/ecospheres/components/BouquetDatasetList.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/139
Plutôt aligné à droite pour éviter l'effet d'escalier sur les longues listes (comme vu sur une maquette).
=> feat: bouquet dataset tag in accordion title

src/custom/ecospheres/views/bouquets/BouquetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/121
Pas dingue parce qu'on a hacké un composant de navigation pas franchement fait pour ça au départ, mais fait le job.
=> fix: bouquets list on mobile

src/assets/main.css, src/custom/ecospheres/components/BouquetDatasetList.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/140
- Ajoute l'affichage par onglets sur la page de détail d'un bouquet
- Mutualise l'affichage de la liste des données avec le parcours de création (such dette technique en moins)
NB: comme pour #361, on rentre dans l'univers graphique data.gouv.fr par le jeu des CSS, donc les boutons sont arrondis.
=> feat: use tabs on bouquet detail

src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/components/datasets/DatasetAddToBouquetModal.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/store/TopicStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/133
- Ajoute la date de modification sur la page de détails d'un bouquet
- Trie les bouquets par date de dernière modification sur la page de liste des bouquets (à discuter ?)
- Utilise le tri du store par date de dernière modification pour calculer les `userTopics`
NB 1 : la date de modification ne sera disponible en prod sur data.gouv.fr que demain au plus tôt
NB 2 : tant qu'un bouquet n'a pas été sauvegardé depuis l'ajout de la date de modification sur data.gouv.fr, sa date de dernière modification est `now()`
=> feat: add topic.last_modifed support

src/custom/ecospheres/components/BouquetList.vue, src/custom/ecospheres/views/bouquets/BouquetsListView.vue, src/store/TopicStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/168
Ajoute un tri sur la liste des bouquets
- Tri par défaut : date de création décroissante
- Modifie le layout de la liste pour se laisser un peu de place pour le tri
- inspiration : https://www.data.gouv.fr/fr/datasets/
- pour l'instant le bouton "Ajouter un bouquet" est remonté et traité en secondaire, voir nouvelles maquettes pour la suite
=> feat(bouquets): add sort on list

configs/defis/config.yaml, configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, package-lock.json, package.json, src/custom/ecospheres/views/HomeView.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/main.js
Related https://github.com/ecolabdata/ecospheres/issues/171
Ajoute des balises meta sur la page de détails d'un bouquet et la home ecosphères :
- title
- description
- og:title
- og:description
- canonical URL
Fun fact : le titre avait "disparu" sur la home, il est de retour.
=> feat(seo): add meta to bouquet detail and home

.github/workflows/node.js.yml, package-lock.json, package.json, src/components/header/Header.vue, src/custom/meteo/assets/datasets.json, src/custom/meteo/views/FormMF.vue
Fix https://github.com/opendatateam/udata-front-kit/issues/309
- Corrige les erreurs Typescript dans les composants TS.
- Ajoute un check CI pour éviter les régressions
Gros refactor de `FormMF`, testé rapidement, @geoffreyaldebert je te laisse vérifier !
@nicolaskempf57 si tu as une idée pour [vue-tsc](https://github.com/opendatateam/udata-front-kit/pull/409/files#diff-014228303dff9a1af15f4bbd18401f906380129b10ae2a2c62f8b8be592ff88eR26), impossible de le faire marcher en 2.x 🤔
=> fix: typescript components syntax

src/model/config.ts, src/router/utils.ts, src/services/routerUtils.js, src/store/OrganizationStore.ts, src/store/TopicStore.ts, src/views/datasets/DatasetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/186
Dans `DatasetsListView`, passe tous les paramètres de recherche en tant que props au composant, liées à la query de l'URL. Ce qui permet :
- de rendre la route/query réactive et donc de la synchroniser dans les deux sens (i.e. je sélectionne une organisation, je mets à jour l'URL ; j'arrive sur une URL avec une organisation, elle est sélectionnée)
- le retour au point de départ depuis une page de détail puisque tous les paramètres sont enregistrés
Les paramètres suivants sont gérés :
- page
- query
- organization (ecosphères)
- topic (météo)
Aussi, refactor `DatasetsListView` et `OrganizationStore` en TS.
=> fix(datasets): persist search params in URL query

src/views/datasets/DatasetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/153
- Exporte la liste de tous les jeux de données de tous les bouquets
- Utilise le Endpoint existant de data.gouv.fr, filtré sur l'univers
- Visible seulement aux admins
- Un poil long à générer mais ça passe encore (5Mo)
- il semble y avoir un cache côté data.gouv.fr, je récupère (rapidement) le même fichier horodaté d'il y a quelques minutes
- Le titre est trop long ;-) mais cf https://github.com/opendatateam/udata-front-kit/pull/417/files#r1549444623
=> feat(bouquets): add global datasets CSV export

src/store/TopicStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/203
Utilise le nouveau paramètres de l'API des topics suite à https://github.com/opendatateam/udata/pull/3007, afin de revenir au comportement existant (charger tous les bouquets en local, quelque soit leur statut).
A gérer plus intelligemment dans https://github.com/ecolabdata/ecospheres/issues/183.
=> chore(bouquets): include_private in API call to list

package-lock.json, package.json, src/custom/ecospheres/components/BouquetDatasetListExport.vue, src/custom/ecospheres/components/forms/bouquet/BouquetFormRecap.vue, src/custom/ecospheres/services/export.ts, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/152
Ajoute un bouton "Exporter les jeux de données" sous la liste des jeux de données d'un bouquet
- sur la page de détail d'un bouquet
- sur la page récapitulative d'un bouquet pre-publish
[65c9f1f19c4ea574470d7553.csv](https://github.com/opendatateam/udata-front-kit/files/14850305/65c9f1f19c4ea574470d7553.csv)
=> feat(bouquets): add datasets CSV export

.github/workflows/robots.yml, scripts/generate-robots-txt.mjs
Tested here on this branch: https://github.com/opendatateam/udata-front-kit/actions/runs/8845558317
=> fix(build): use VITE_SITE_ID instead of CONFIG_NAME for robots

configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/171
:warning: Cible `ecospheres-demo` au lieu de `ecospheres-prod` pour le diff, en attendant le merge de https://github.com/opendatateam/udata-front-kit/pull/440.
La PR sera rebased sur `ecospheres-prod` pour le merge.
=> Prod robots config

src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
A déployer en prod ASAP.
Voir ce qu'on fait avec le stock. Cette propriété n'est malheureusement ou heureusement pas utilisée dans le cas `LOCAL_AVAILABLE`.
=> fix(bouquet): use correct route for dataset.uri

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/views/datasets/DatasetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/187
Affiche un warning sur le score qualité quand le jeu de données est moissonné via une liste configurable de backends.
Exemple de dataset qui doit déclencher le warning : `1338-marina-di-carrara`.
=> feat(bouquet): add harvested dataset quality warning

configs/ecospheres/config.yaml, configs/meteo-france/config.yaml, src/components/datasets/ExtendedInformationPanel.vue, src/model/dataset.ts, src/views/datasets/DatasetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/219
Fix https://github.com/ecolabdata/ecospheres/issues/234
Fix https://github.com/ecolabdata/ecospheres/issues/235
Ajoute l'affichage de métadonnées supplémentaires pour un jeu de données (configurable) :
- Point de contact (`dataset.contact_point`)
- Conditions d'accès et d'utilisation (`dataset.extras.harvest['dct:accessRights']`)
- Généalogie (`dataset.extras.harvest['dct:provenance']`)
Une section "Informations étendues" s'ajoute au dessus du panneau d'information "standard" de data.gouv.fr. Peut-être revoir le wording du titre de la section. Afin de mieux mettre en valeur ces métadonnées, elles s'affichent au-dessus des autres informations existantes.
- Exemple point de contact et conditions (mauvaise qualité) : …
=> feat(dataset): add extended information panel

src/custom/ecospheres/components/BouquetDatasetList.vue
Fix https://github.com/ecolabdata/ecospheres/issues/226
- Collapse la liste avant de la réorganiser
- Utilise une liste (au sens HTML) dédiée pour la réorganisation, sans fonctionnalité de collapse (et donc sans suppression / édition)
- Synchronise l'état du collapse lors de la suppression d'un jdd
Collapse la liste plutôt que tenter de synchroniser l'ordre lors d'une réorganisation : difficile en l'absence d'identifiant pour un jeu de données (`datasetProperties`).
=> fix(bouquets): handle collapse state when list is edited

configs/ecospheres/config.yaml, src/custom/ecospheres/components/BouquetDatasetList.vue, src/custom/ecospheres/components/forms/dataset/DatasetEditModal.vue
Fix https://github.com/ecolabdata/ecospheres/issues/218
- Détecte une URL manuelle data.gouv.fr à la soumission de la modale de création / édition d'un jeu de données et remplit le cas échéant les métadonnées pour un jeu de données `LOCAL_AVAILABLE`.
- Refactor la modale dans son propre composant afin de ne pas avoir un composant `BouquetDatasetList` trop gros
Fait de manière silencieuse car ça me parait acceptable et c'est définitivement plus simple.
Pour l'instant on ne peut pas attraper l'erreur 404 correctement, pending https://github.com/datagouv/data.gouv.fr/issues/1359, donc c'est un peu moche dans ce cas. Ca ne devrait pas arriver souvent donc je pense qu'on peut merger ça et traiter le FIXME plus tard.
=> feat(bouquet): auto handle data.gouv.fr URL in dataset

src/components/OrganizationLogo.vue, src/custom/ecospheres/components/forms/bouquet/BouquetOwnerForm.vue, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/custom/ecospheres/views/bouquets/BouquetFormView.vue, src/model/user.ts, src/store/UserStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/89
- Ajoute la possibilité d'associer un bouquet à une organisation de l'utilisateur connecté
- Permet aux membres de l'organisation d'éditer un bouquet
Une section "Propriétaire du bouquet" apparait en bas dans le formulaire d'édition/création. Wording à valider / revoir. Placé en bas car probablement pas la première chose à laquelle on a envie de réfléchir en créant un bouquet, ni la première chose à modifier. On peut sélectionner "en son propre nom" ou une organisation à laquelle on appartient (similaire à la création d'un jeu de données sur data.gouv.fr).
Le fait que le formulaire "propriétaire" soit disponible en édition permet à chaque membre de l'organisation de s'attribuer le bouquet en son nom ou dans le déplacer dans une autre …
=> feat(bouquet): link to organization

src/custom/ecospheres/components/forms/dataset/DatasetEditModal.vue, src/custom/ecospheres/utils/bouquet.ts, src/main.ts, src/model/api.ts, src/services/api/DatagouvfrAPI.ts, src/services/api/SearchAPI.ts, src/services/api/SpatialAPI.ts, src/services/api/__tests__/DatagouvfrAPI.test.ts, src/store/DatasetStore.ts, src/store/DiscussionStore.ts, src/store/OrganizationStore.ts, src/store/ResourceStore.ts, src/store/ReuseStore.ts, src/store/TopicStore.ts, src/store/UserStore.ts, src/views/LoginView.vue
Introduit les paramètres suivants pour chaque appel d'API :
- `toasted` : est-ce qu'un toast doit être affiché en cas d'erreur ?
- `authentificated` : est-ce que la clé d'API doit être envoyée si elle existe ?
Ces changements permettent :
- d'ignorer silencieusement une erreur réseau
- de contourner https://github.com/datagouv/data.gouv.fr/issues/1359 en n'envoyant la clé d'API seulement quand c'est nécessaire, et donc de ne pas avoir (la plupart du temps) d'erreur CORS sur les 3xx, 4xx et 5xx au GET
On peut ainsi traiter les deux `FIXME` :
- dataset non trouvé sur data.gouv.fr quand on tente d'auto-remplacer un jeu de données référence via URL dans un bouquet
- bouquet `cloned_from` non trouvé (parce que supprimé probablement)
Cela ouvre aussi la possibilité de traiter …
=> refactor: toasted and authenticated config params for API methods

src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/217 
(techniquement déjà fixé par https://github.com/opendatateam/udata-front-kit/pull/464)
Redirige un ancien slug ou un id vers le slug courant du bouquet.
Utilise aussi le slug pour l'URL canonique, cf https://github.com/ecolabdata/ecospheres/issues/171#issuecomment-2139646092
=> feat(bouquet): handle redirect

public/_redirects, src/custom/ecospheres/views/bouquets/BouquetDetailView.vue, src/main.ts, src/model/api.ts, src/router/index.ts, src/services/api/DatagouvfrAPI.ts, src/store/OrganizationStore.ts, src/views/NotFoundView.vue, src/views/datasets/DatasetDetailView.vue, src/views/organizations/OrganizationDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/215
Ajoute une page "Page non trouvée" vers laquelle on est redirigé quand on accède à :
- un bouquet qui n'existe pas
- une organisation qui n'existe pas
- un bouquet qui n'existe pas
- une route qui n'existe pas
Il ne s'agit pas d'une "vraie" page 404 car le code de retour sera 200, à cause de l'architecture SPA. Il faudrait faire quelque chose d'un peu compliqué pour faire mieux : rediriger vers une page serveur qui retourne une 404. Vu la complexité et le peu d'intérêt (la redirection serait faite en JS, donc un curl ou autre n'y verrait que du feu), j'ai choisi de rester (relativement) simple.
=> feat(bouquet): handle 404

.vscode/extensions.json, README.md
- Volar est renommé en Vue - officiel (l'id de l'extension reste le même)
- Le plugin Typescript vue est maintenant inclus dans Vue - officiel
- Ajout du plugin Eslint aux recommandations
=> Mise à jour des recommandations vscode

src/views/datasets/DatasetDetailView.vue
Lorsqu'un dataset est moissoné depuis une source externe, un lien vers l'url est affiché comme dans data.gouv.
Utilisation du composant DSFR [AppLink](https://669123cd8a2c1ef63abe6805-twdpyxdyhx.chromatic.com/?path=/docs/components-applink--docs).
Y aurait-t-il une utilité à en faire un composant à part entière ?
Fix https://github.com/ecolabdata/ecospheres/issues/288
=> Affichage d'un lien vers la source externe d'un dataset

src/components/forms/dataset/SelectDataset.vue
En attendant de savoir s'il faut redesigner ou masquer cet élément, je l'ai positionné sous les autres éléments de la carte.
Inconvénient: lors de son apparition, il pousse un peu les cartes suivantes vers le bas.
Fix https://github.com/ecolabdata/ecospheres/issues/294
=> Fix: overlaping elements on multiselect list

src/assets/main.css, src/components/datasets/DatasetAddToBouquetModal.vue, src/components/forms/dataset/DatasetCardForSelect.vue, src/components/forms/dataset/SelectDataset.vue, src/views/bouquets/BouquetDetailView.vue
- J'ai autorisé la sélection du même jeu de données dans un seul bouquet.
- J'ai cependant ajouté un avertissement lors de la sélection afin que l'utilisateur identifie facilement les datasets déjà utilisés. Initiative personnelle, à voir si ça vous plaît !
- J'ai également supprimé la prop `max-height` du `Multiselect` car ça causait un overflow lors de la sélection:
- J'ai dû forcer l'icône du [badge](https://vue-ds.fr/composants/DsfrBadge) car il allait la chercher ici `../../icons/system/fr--warning-fill.svg` et ne la trouvait pas.
Fix https://github.com/ecolabdata/ecospheres/issues/206
fix https://github.com/ecolabdata/ecospheres/issues/233
=> feat: Allow adding the same dataset multiple times to a bouquet.

src/components/forms/bouquet/BouquetOwnerForm.vue, src/model/organization.ts, src/services/api/SearchOrgAPI.ts
Possibilité pour un admin de modifier le propriétaire d'un bouquet vers n'importe quelle organisation existante sur data gouv.
J'ai modifié la structure HTML existante pour utiliser le DSFR si possible.
Ajout de la structure nécessaire (model + service) à l'API des organisations. 
FIX https://github.com/ecolabdata/ecospheres/issues/278
=> Feat: assign bouquet to any organization

src/components/forms/SelectSpatialCoverage.vue, src/components/forms/bouquet/BouquetForm.vue
Fix https://github.com/ecolabdata/ecospheres/issues/461
=> Fix spatial coverage not saved

src/components/header/HeaderComponent.vue
Fix : https://github.com/ecolabdata/ecospheres/issues/473
=> Fix spaces & alignments on header nav

index.html
Fix: https://github.com/ecolabdata/ecospheres/issues/450
=> Display a message when the user has JavaScript disabled.

src/components/DiscussionsList.vue, src/main.ts
Fix: https://github.com/ecolabdata/ecospheres/issues/401
=> Fix login on discuss

src/components.d.ts, src/components/SearchComponent.vue, src/components/header/HeaderComponent.vue, src/custom/ecospheres/views/HomeView.vue, src/views/bouquets/BouquetsListView.vue, src/views/datasets/DatasetsListView.vue
Fix: https://github.com/ecolabdata/ecospheres/issues/407
=> Use `SearchComponent` on bouquets & données page

src/services/api/resources/DatasetsAPI.ts, src/store/DatasetStore.ts, src/utils/index.ts, src/views/organizations/OrganizationDetailView.vue
- Corrige les erreurs de linting / typage sur `OrganizationDetailView`
- Corrige le tri (avec un TODO sur le tri par défaut dépendant de #605)
- Utilise les `DatasetCard` de data.gouv.fr pour la liste des jeux de données
- Migre les misc utils en Typescript
=> feat(organization): quick redesign of datasets list

src/store/UserStore.ts
Related https://github.com/ecolabdata/ecospheres/issues/523
=> fix: login flow after bad token

src/views/bouquets/BouquetFormView.vue
Cette partie du formulaire ne fonctionne plus suite à des changements sur l'API data.gouv.fr.
Related https://github.com/ecolabdata/ecospheres/issues/528
=> fix: disable bouquet ownership form during edition

configs/ecospheres/config.yaml, public/ecospheres/pages/about.md, public/ecospheres/pages/accessibility.md, src/assets/main.css, src/components/OrganizationCard.vue, src/components/bouquets/BouquetCard.vue, src/components/bouquets/BouquetDatasetList.vue, src/components/bouquets/BouquetGroup.vue, src/components/bouquets/BouquetList.vue, src/components/forms/bouquet/BouquetOwnerForm.vue, src/components/forms/dataset/DatasetCardForSelect.vue, src/components/header/HeaderComponent.vue, src/custom/ecospheres/components/HomeFaq.vue, src/custom/ecospheres/components/indicators/IndicatorList.vue, src/custom/ecospheres/views/HomeView.vue, src/views/bouquets/BouquetDetailView.vue
Fix layout quirks.
Fix horizontal scrolling.
Proposal for enhanced responsive.
fix https://github.com/ecolabdata/ecospheres/issues/509
=> Fix: homepage styles

configs/meteo-france/config.yaml
Reverse engineered from https://meteo.data.gouv.fr/, seems to be a missing class in the config file.
=> fix: meteo hp sub_section_tiles.class

src/App.vue, src/components/SkipLinks.vue
Enhance behaviour of skip link focus.
fix: https://github.com/ecolabdata/ecospheres/issues/529
=> fix: a11y skiplinks

src/store/TopicStore.ts
La liste des Topics sur l'API est désormais sensible à l'utilisateur courant pour récupérer ou non les brouillons https://github.com/opendatateam/udata/pull/3265. On utilise donc l'API en mode `authenticated` pour récupérer les brouillons.
=> bouquets: authenticate list API call

src/components/datasets/ExtendedInformationPanel.vue, src/components/datasets/ExtendedInformationPanelItem.vue, src/model/dataset.ts
Fix https://github.com/ecolabdata/ecospheres/issues/534
data.gouv.fr expose maintenant (fait en démo, en prod d'ici fin de semaine) les points de contact sous forme de liste https://github.com/opendatateam/udata/pull/3149.
Cette PR permet de gérer une liste vs un item unique.
data.gouv.fr introduit aussi une notion de `role`. Pour l'instant (iso-fonctionnel), on n'affiche que `role == contact`. Vu avec data.gouv.fr, se synchroniser pour voir le traitement sur les autres rôles.
Au passage :
- meilleur typage de `dcatExtras` (crash sur `service-de-force-de-securite-2` fixé)
- meilleur typage du `contactPoint` en fonction du modèle udata
Exemples :
- `point-numerique-cc-grand-chambord`
- `5808de39c751df1e0679df72`
- `67b42e2a11a9813d380bbd5b` (multiple)
=> fix: handle multiple contact points

configs/ecospheres/config.yaml, src/components/bouquets/BouquetDatasetCard.vue, src/components/bouquets/BouquetDatasetList.vue, src/components/datasets/ResourcesList.vue, src/components/forms/dataset/DatasetCardForSelect.vue, src/custom/ecospheres/components/indicators/IndicatorDatasetCard.vue, src/custom/ecospheres/store/IndicatorStore.ts, src/custom/ecospheres/utils/indicator.ts, src/model/DatasetV2Fix.ts, src/utils/avatar.ts, src/utils/dataset.ts
Fix https://github.com/ecolabdata/ecospheres/issues/530
Fix https://github.com/ecolabdata/ecospheres/issues/532
Fix https://github.com/ecolabdata/ecospheres/issues/533
- Utilise le nouvel identifiant d'organisation Ecolab en demo
- Ajoute un filtre global sur le tag `ecospheres-indicateurs` pour la liste des indicateurs, afin de discriminer les indicateurs des autres jeux de données
- Utilise cette nomenclature pour différencier un indicateur d'un autre jeu de données dans la composition d'un bouquet et
- affiche une pastille "Indicateur" sur la carte d'un indicateur (il a fallu recréer une carte dédiée, on n'a pas la main sur celle des datasets)
- renvoie vers le page de détail d'un indicateur au clic sur sa carte
Nécessite de taguer correctement les indicateurs existants pour tout voir …
=> feat: improve indicators in bouquets

src/components/SearchComponent.vue, src/components/datasets/DatasetAddToBouquetModal.vue, src/components/forms/ErrorMessage.vue, src/components/forms/ErrorSummary.vue, src/components/forms/SelectTopicGroup.vue, src/components/forms/bouquet/BouquetForm.vue, src/components/forms/dataset/DatasetEditModal.vue, src/components/forms/dataset/DatasetPropertiesFields.vue, src/components/forms/dataset/DatasetPropertiesTextFields.vue, src/components/forms/dataset/SelectDataset.vue, src/store/SearchStore.js, src/utils/form.ts, src/views/bouquets/BouquetsListView.vue, src/views/datasets/DatasetsListView.vue, vite.config.mts
fix https://github.com/ecolabdata/ecospheres/issues/224
fix https://github.com/ecolabdata/ecospheres/issues/381
=> fix: forms

src/components/bouquets/BouquetDatasetCard.vue
Un couplage entre bouquet et indicateurs a été introduit dans #666.
Ce couplage pose problème sur les autres verticales qui utilise les bouquets (crash page bouquet sur météo par exemple).
Cette PR propose un import conditionnel des modules et composants nécessaires aux indicateurs seulement dans le cas d'Ecosphères.
=> fix: conditional import of indicator in bouquet

src/utils/bouquet.ts, src/views/bouquets/BouquetDetailView.vue, src/views/bouquets/BouquetFormView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/531
@Thesauruv je veux bien ton avis sur le wording, pas facile d'être clair.
=> feat: clone while keeping datasets (or not)

configs/ecospheres/config.yaml
We decided not to display in the list of "levier" the ones that were not yet associated to an indicator in order to improve the user search experience on the website.
I left only 18 leviers that were already attached to an indicator
=> Remove un-used "levier" from config.yaml

.env, configs/logistique/config.yaml
Depends on https://github.com/opendatateam/udata-front-kit/pull/661
Conversion des thèmes en tags après passage du script de migration https://github.com/ecolabdata/ecospheres-scripts/pull/17.
Cf la discussion sur les couleurs des tags et l'affichage du thème dans la carte https://github.com/opendatateam/udata-front-kit/pull/661#discussion_r1990897936. Dans le cas de logistique, je trouve que ça marche bien.
=> chore(logistique): themes as tags

.github/workflows/review-app.yml
Sans cela, trop facile d'injecter un payload malicieux depuis n'importe quel repo.
=> fix: allow pr previews only from same repo

configs/ecospheres/config.yaml, src/components/datasets/DatasetList.vue, src/custom/ecospheres/components/datasets/EcospheresDatasetSearch.vue, src/store/DatasetSearchStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/550
Ajoute un filtre sur les thèmes Inspire pour les jeux de données de ecologie.data.gouv.fr.
Les thèmes proviennent de https://inspire.ec.europa.eu/theme/theme.fr.json, le tag est construit en passant le `slugify` de data.gouv.fr sur le `label.text` (équivalent à ce qui est fait au moissonnage).
=> feat(ecospheres/datasets): add inspire themes filter

.github/workflows/review-app.yml
Fix https://github.com/ecolabdata/ecospheres/issues/553
Il semblerait qu'il faille expliciter les événements `pull_request` pour être certain d'attraper le `closed` 🤷 🍿 🤞.
=> fix: destroy review app on PR close

configs/ecospheres/config.yaml, src/assets/main.css, src/custom/ecospheres/views/HomeView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/558
Pending https://github.com/ecolabdata/ecospheres/issues/551
Ajoute un fond ~~vert~~ bleu sur la section bouquets de la HP, ainsi que sur les différents bandeaux. Corrige aussi le noir des titres (à passer quoiqu'il arrive).
=> feat(ecologie): home page and banner color 🟦 

configs/ecospheres/config.yaml
Reprend les labels des thématiques des indicateurs (sans changer les identifiants, pour éviter une migration des tags). Reprend aussi l'ordre des indicateurs, sauf "Autre" qui passe en bas des deux listes.
Fix https://github.com/ecolabdata/ecospheres/issues/552
=> chore(ecologie): themes list labels coherence

src/custom/ecospheres/views/HomeView.vue, src/store/TopicStore.ts, src/views/topics/TopicDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/399
Depends https://github.com/opendatateam/udata/pull/3301
Les pastilles sont légèrement différentes vs la maquette, il s'agit d'un `DsfrTag` standard.
---
=> feat(topic): featured topics

src/views/topics/TopicDetailView.vue
Depuis https://github.com/opendatateam/udata-front-kit/pull/745, le bouton "Cloner" est visible par tous sur ecologie.data.gouv.fr, sans même être connecté.
Toutefois, l'affichage du bouton Cloner doit être conditionné au fait que la configuration du site permet d'ajouter des Topics.
=> fix(topic): clone button visibility

.github/workflows/review-app.yml, README.md
Adds a comprehensive deployment section to document the automated deployment process for thematic verticals.
Some users of this repository expressed confusion about how to deploy and how the deployment process works. This PR addresses those questions by providing clear documentation.
- **New "Déploiement" section** explaining the GitHub workflow triggered by commit message format
- **Deployment parameters** documentation (ENV, CONFIG_NAME, VERSION_PART)
- **Commit message format** with example: `[prod:ecologie:minor] new feature`
- **Workflow steps** and **deployment architecture** (GitHub → GitLab for security)
- **Direct link** to workflow file and **deployment tracking limitations**
- Automatic deployment triggered by commit message format
- Secure architecture with GitHub (code) / …
=> docs: update docs about deployment

src/components/SearchComponent.vue, src/components/header/HeaderComponent.vue
Fix https://github.com/ecolabdata/ecospheres/issues/654
Fix https://github.com/ecolabdata/ecospheres/issues/677
Ajoute un attribut `title` aux champs de recherche, avec la même valeur que `placeholder`. Pas possible pour `DsfrSearchBar` (non utilisé sur ecologie.data.gouv.fr), donc FIXME.
=> fix(rgaa): title on search fields

.github/workflows/review-app.yml
`app:exists` n'était pas appelé avec les bons arguments SSH (clé privée). On utilise ici l'action `appleboy/ssh-action` déjà utilisée dans le script pour récupérer le code retour de `app:exists` puis alimenter `$APP_EXISTS`.
=> fix(ci): review app existence check

src/custom/simplifions/components/SimplifionsRecoSolutions.vue, src/custom/simplifions/components/SimplifionsSolutionDescription.vue, src/router/utils.ts
Injecting `pageKey` in props forces the detail page to remount when switching page type.
=> fix: force page remount when switching detail pages

.github/workflows/create-deploy-release.yml
Tentative pour résoudre le bug de CI mentionné ici : https://github.com/opendatateam/udata-front-kit/pull/810#issuecomment-3117521750
L'étape "Parse commit message" utilise working-directory: ${{ env.APP_NAME }} mais cette étape s'exécute avant que le repository soit cloné.
Ajout aussi d'une condition pour lancer le CI job uniquement si c'est via un input manuel ou bien si c'est un push avec un message de commit qui commence par "[".
=> ci: fix CI deploy bug

configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/564
Active la recherche depuis le "mega search" dans les indicateurs.
=> feat(indicators): mega search

src/custom/ecospheres/components/indicators/informations/InformationPanelSection.vue
Fix https://github.com/ecolabdata/ecospheres/issues/685
Je n'ai pas trouvé de double `<br>` et le rapport n'en montre pas.
=> fix(rgaa): empty p blocks

src/views/topics/TopicDetailView.vue
Disable edition of Topic for ecospheres until "empty bouquet when PUT" bug is fixed.
=> hotfix: disable edit and featured for ecospheres

src/components/forms/dataset/FactorEditModal.vue
Do not make title mandatory when dataset_editorialization is not enabled.
=> fix: mandatory title when not dataset_editorialization
