- .gitignore
- config.yaml
- src/components/Navigation.vue
- src/composables/fetch.js
- src/router/index.js
- src/services/api/DatagouvfrAPI.js
- src/services/api/resources/Organizations.js
- src/views/organizations/OrganizationDetailView.vue
- src/views/organizations/OrganizationsListView.vue
- add minimal organization detail page
- add organisations list page (based on config)
- add API wrapper for organizations endpoints
> Add organization pages

- config.yaml
@abulte Feel free to modify the list if this is too much for a start.
> Add MCT, DDT, DREAL, DEAL to org list

- .env
- .env.production
- .gitignore
- README.md
- index.html
- package-lock.json
- package.json
- src/App.vue
- src/router/index.js
- src/services/api/DatagouvfrAPI.js
- src/services/api/SearchAPI.js
- src/store/index.js
- src/views/datasets/DatasetsListView.vue
Designed to work with https://github.com/abulte/ecospheres-search-index, based on Meilisearch.
Not sure if we'll go with this but I guess it shows it can be quite simple, at least for basic features.
> External search prototype

- src/views/datasets/DatasetDetailView.vue
- src/views/organizations/OrganizationDetailView.vue
Fix and simplify pagination when using watchEffect to handle reactive ids (introduced in #35)
> Fix paginations when using watchEffect()

- src/App.vue
- src/services/api/DatagouvfrAPI.js
- src/services/api/resources/DatasetsAPI.js
- src/store/DatasetStore.js
- src/store/OrganizationStore.js
- src/views/organizations/OrganizationDetailView.vue
- deterministic sort order for orgs view
- sort widget for org's dataset 
@streino feel free to merge!
> Improvements on lists

- src/views/datasets/DatasetDetailView.vue
> [datasetDetail] Add quality tab

- src/store/OrganizationStore.js
> Fix organizations pagination

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- package.json
Thanks for contributing to Ecosphères!
Supercedes #58
Fixes #78 
> User: Product manager.
>
> When I'm populating and grooming the backlog,
> I want to have a simple issue and pull request template,
> so I can provide a structured template that facilitates communication with all stake holders.
> Add issue and pull request template

- README.md
- package-lock.json
- package.json
Closes #66
> Utilisateur : développeur·e
>
> Quand je code,
> je veux écrire des tests d'abord,
> pour être sûr que le code sera de meilleure qualité.
Lorsque je tape `npm run test`, je m'attends à ce qu'il y ait une batterie de tests automatisés.
```
➜  npm run test
> ecospheres-front@X.Y.Z test
> vitest
DEV  v0.34.6 XXX
✓ XXX
✓ XXX
✓ XXX
Test Files  X passed (X)
Tests  X passed (X)
```
Ce n'était pas le cas.
```
➜  npm run test
npm ERR! Missing script: "test"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```
- Testing avec Vitest
> build(npm): add testing framework and tasks

- CONTRIBUTING.md
- package-lock.json
- package.json
Closes #61 
> User: Multi, Ecolab, contributors.
>
> When we are getting ready to launch "Écosphères Beta",
> we want to be able to roll out each changeset continuously,
> so that we can get them into the hands of users as quickly as possible.
When I want to contribute to the code, I expect a CONTRIBUTING.md file to exist.
It does not.
Add a CONTRIBUTING.md file.
- Add a proposal for a contributing policy.
> chore(policy): add a CONTRIBUTING.md file

- src/views/bouquets/BouquetDetailView.vue
- src/views/bouquets/BouquetsListView.vue
Supersedes #95 
- Show bouquet creation button to everyone
- Show edit button to admin or owner of the bouquet
> feat(topics): allow non admin to create and edit

- src/services/api/DatagouvfrAPI.js
- src/services/api/__tests__/DatagouvfrAPI.test.js
> Fix DatagouvfrAPI constructor

- .github/workflows/node.js.yml
- package.json
> chore(ci): add tests

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Closes #142 
> Title : _Traduit les templates github en FR_
> User: _Multi, Ecolab, Agent·e·s, Contributrices et contributeurs_
>
> When I want to contribute to Écosphères,
> I want to read the issues in Github in French,
> so to understand quickly what is going on in the lingua franca of Frech public services.
Everything is in English.
None yet, but foreseen: difficulty to comunicate about and to participate to the discussion.
Write issues and pull requests in French.
- 📖 Translate issue and pull request templates in French.
> policy: traduit les templates github en FR

- src/views/HomeView.vue
> fix(home): conditionnal HomeThemes

- vite.config.ts
Relates to #190
Fixes https://github.com/ecolabdata/ecospheres-front/pull/190#issuecomment-1829761547
> build(vite): add vite esm bundler

- package.json
> build(npm): disable --fix from eslint

- package-lock.json
- package.json
- src/main.js
- src/views/HomeView.vue
- src/views/datasets/DatasetDetailView.vue
Close https://github.com/ecolabdata/ecospheres-front/issues/188
> Added the npm package @etalab/data.gouv.fr-components + replaced DsfrFileDownloadList by ResourceAccordion

- configs/meteo-france/config.yaml
- src/components/HomeTopics.vue
- styling for home topics cards (without image, just simple cards)
- update config for MF (secondary)
> feat: style home topics

- configs/meteo-france/config.yaml
> config: meteo.data.gouv.fr

- configs/ecospheres/config.yaml
- configs/meteo-france/config.yaml
- package-lock.json
- package.json
- src/views/datasets/DatasetDetailView.vue
Close https://github.com/ecolabdata/ecospheres-front/issues/213
Close https://github.com/ecolabdata/ecospheres-front/issues/218
Close https://github.com/etalab/data.gouv.fr/issues/1220
> feat: :sparkles: Added QualityComponent and ReadMore on dataset page

- src/custom/meteo/views/FormMF.vue
- src/views/datasets/DatasetsListView.vue
- src/views/organizations/OrganizationsListView.vue
- 🤟 Correction des temps et termes utilisés
> Harmonize tense and use browse term

- src/services/routerUtils.js
Close https://github.com/ecolabdata/ecospheres-front/issues/252
> fix: :bug: edited router call for FormMF to avoid crash in prod

- configs/ecospheres/config.yaml
- configs/meteo-france/config.yaml
- public/meteo-france/pages/about.md
- public/meteo-france/pages/accessibility.md
- src/App.vue
- src/components/footer/Footer.vue
Custom  footer with data.gouv.fr style
> feat: add custom footer with data.gouv.fr style

- configs/meteo-france/config.yaml
- public/meteo-france/pages/about.md
- src/custom/meteo/assets/datasets.json
- src/custom/meteo/views/FormMF.vue
> fix: wordings for meteo.data.gouv.fr

- src/components/HomeTopics.vue
- src/components/footer/Footer.vue
- src/custom/meteo/views/FormMF.vue
- src/views/HomeView.vue
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
various fixes.
- ajout du bleu data.gouv.fr dans des reliquats d'interfaces
- enlèvement de l'onglet "qualité" qui n'a plus lieu d'être car le score est affiché à droite de la page jeu de données
- quelques fix pour meteo.data
- ~~agrandissement de la police de la tagline sur la home~~
- interface de datasetslist plus adapté pour meteo.data (où l'on filtre par thématique)
> fix: various style fixes for meteo.data

- src/components/footer/Footer.vue
Fix pour enlever un warning dans la console.
> fix: operatorImgAlt undefined property

- configs/ecospheres/config.yaml
- configs/meteo-france/config.yaml
- package-lock.json
- package.json
- src/App.vue
- src/components/HomeTopics.vue
- src/components/Navigation.vue
- src/components/footer/Footer.vue
- src/components/header/Header.vue
Fixes https://github.com/etalab/data.gouv.fr/issues/1239
Fixes https://github.com/etalab/data.gouv.fr/issues/1238
- 🛠 Correction de l'affichage des topics de la home en responsive
- 🛠 Correction de la fermeture de menu en responsive
- 🛠 Correction de l'affichage du footer en responsive
- 🛠 Correction de l'affichage de la carte jeu de données en responsive
- 🛠 Ajout d'un `alt` sur le serviceLogo du header
> Fix responsive issues

- src/custom/meteo/views/FormMF.vue
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
- src/views/organizations/OrganizationDetailView.vue
- src/views/organizations/OrganizationsListView.vue
Close https://github.com/etalab/data.gouv.fr/issues/1241
> fix: reduced space between titles and subtitles on all pages

- src/views/datasets/DatasetDetailView.vue
Close https://github.com/etalab/data.gouv.fr/issues/1247
Close https://github.com/etalab/data.gouv.fr/issues/1248
> feat: :sparkles: Added number of resources for DatasetDetailView

- src/views/datasets/DatasetsListView.vue
Close https://github.com/etalab/data.gouv.fr/issues/1251
> fix: change thematic selector's padding in DatasetsListView

- src/custom/meteo/views/FormMF.vue
Close https://github.com/etalab/data.gouv.fr/issues/1249
> feat: added line break in formMF text

- src/components/DiscussionsList.vue
> feat(discussion): do not parse markdown

- src/views/datasets/DatasetDetailView.vue
Close https://github.com/etalab/data.gouv.fr/issues/1250
> fix: :lipstick: Edited button in discussions well to fit data.gouv design

- src/App.vue
- src/components/header/Header.vue
- src/views/datasets/DatasetsListView.vue
Close https://github.com/etalab/data.gouv.fr/issues/1260
Close https://github.com/etalab/data.gouv.fr/issues/1259
> feat: :sparkles: Add a search bar on DatasetsList + header searchbar empties itself on search action

- configs/meteo-france/config.yaml
- public/meteo-france/pages/about.md
Config : rework meteo.data.gouv.fr to get back to main code with actual prod config
No impact for ecospheres
> config: meteodatagouvfr

- README.md
Mise à jour et traduction du README
Fix #62
> Mise à jour de README.md pour udata-front-kit

- configs/meteo-france/config.yaml
- src/custom/meteo/assets/datasets.json
- src/custom/meteo/views/FormMF.vue
- Add pnt topic
- reshape custom form
> add: pnt topic

- src/custom/ecospheres/components/BouquetList.vue
- src/custom/ecospheres/views/bouquets/BouquetAddView.vue
- src/custom/ecospheres/views/bouquets/BouquetEditView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/103
> feat(bouquet): prefill theme and subtheme

- src/custom/ecospheres/components/forms/bouquet/BouquetContentFieldGroup.vue
- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesForm.vue
Fix https://github.com/ecolabdata/ecospheres/issues/95
> feat(bouquet): watch dirty state from add dataset form

- configs/ecospheres/config.yaml
> Ajout du siteId matomo pour Ecosphères

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/94
> Ajout du bouton 'Donnez votre avis' sur ecologie.dgfr

- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesForm.vue
Fix https://github.com/ecolabdata/ecospheres/issues/119
NB: pas la possibilité d'utiliser de l'_italique_
> fix(bouquet): ecospheres -> ecologie.dgf in dataset add

- src/custom/ecospheres/components/BouquetList.vue
- src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/157
Fix https://github.com/ecolabdata/ecospheres/issues/158
> fix: bouquet nav (breadcrumb, go back)

- src/custom/ecospheres/views/bouquets/BouquetEditView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/160
> fix: align buttons step 1 bouquet edit

- src/custom/ecospheres/components/BouquetDatasetAvailability.vue
Fix https://github.com/ecolabdata/ecospheres/issues/163
> fix: fr-tag style leak

- public/ecospheres/pages/terms.md
> Terms: add Freepic to credits

- src/custom/ecospheres/views/HomeView.vue
Follow-up https://github.com/ecolabdata/ecospheres/issues/99
@martyKN n'hésite pas à faire un passage sur tout le wording et mettre tes suggestions ici.
> Reformulation home page

- src/custom/ecospheres/components/BouquetDatasetAvailability.vue
Fix https://github.com/ecolabdata/ecospheres/issues/166
> Fusion des labels "Donnée non disponible" et "Donnée manquante" en "Non disponible"

- src/custom/ecospheres/components/BouquetDatasetAccordionTitle.vue
- src/icons.js
Fix https://github.com/ecolabdata/ecospheres/issues/170
> Change bouquet dataset list drag indicator

- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
Fix https://github.com/ecolabdata/ecospheres/issues/169
> fix(bouquet): show selected dataset on edit

- src/views/datasets/DatasetDetailView.vue
Fixes https://github.com/opendatateam/udata-front-kit/issues/342
> Fix DsfrTabs height not updating when expanding an accordion in informations tab

- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
- src/model/api.ts
- src/services/api/SearchAPI.ts
Fix https://github.com/ecolabdata/ecospheres/issues/177
> feat(bouquet): search dataset from all data.gouv.fr

- src/components/HomeThemes.vue
Fix https://github.com/ecolabdata/ecospheres/issues/175
> feat(bouquets): add bouquets count on home

- src/custom/ecospheres/components/BouquetDatasetAvailability.vue
- src/custom/ecospheres/components/BouquetDatasetCard.vue
- src/custom/ecospheres/components/BouquetDatasetList.vue
- src/custom/ecospheres/components/BouquetSearch.vue
- src/custom/ecospheres/components/forms/bouquet/BouquetContentFieldGroup.vue
- src/custom/ecospheres/components/forms/bouquet/BouquetFormRecap.vue
- src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
- src/utils/bouquet.ts
- src/views/datasets/DatasetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/159
Fix https://github.com/opendatateam/udata-front-kit/issues/178 🍾 🎉 🕺
> feat(bouquets): dataset card in bouquet

- src/custom/ecospheres/components/forms/bouquet/BouquetPropertiesFieldGroup.vue
- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesTextFields.vue
Fix https://github.com/ecolabdata/ecospheres/issues/178
Fix https://github.com/ecolabdata/ecospheres/issues/179
> chore(bouquet): update form wording

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/182
> Sync config main avec branche ecospheres-demo

- configs/ecospheres/config.yaml
La précédente modif reprenait les orgs de prod, qui sont différentes de demo.
> Fix demo org list

- src/custom/ecospheres/components/BouquetList.vue
- src/custom/ecospheres/components/BouquetSearch.vue
- src/custom/ecospheres/components/forms/SelectSpatialCoverage.vue
- src/custom/ecospheres/components/forms/bouquet/BouquetInformationsFieldGroup.vue
- src/custom/ecospheres/views/bouquets/BouquetAddView.vue
- src/custom/ecospheres/views/bouquets/BouquetEditView.vue
- src/custom/ecospheres/views/bouquets/BouquetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/134
@streino Tu peux voir le coût de l'ajout de la synchronisation de l'URL sur geozone dans https://github.com/opendatateam/udata-front-kit/commit/0991e96300aec9b60c1f32dca987e526bd498f61. Je l'ai ajoutée pour pouvoir pré-remplir la geozone en cliquant sur "Ajouter un bouquet", comme pour le thème.
> feat(bouquets): filter list on spatial zone

- configs/ecospheres/config.yaml
- package-lock.json
- package.json
Fix https://github.com/opendatateam/udata-front-kit/issues/337
Met à jour la dépendance `vue-dsfr` avec la PR qui va bien https://github.com/dnum-mi/vue-dsfr/pull/782
> chore: upgrade @gouvminint/vue-dsfr

- .github/workflows/node.js.yml
- package-lock.json
- package.json
- src/components/header/Header.vue
- src/custom/meteo/assets/datasets.json
- src/custom/meteo/views/FormMF.vue
This PR adds 2 new MF datasets to the datasets.json.
It also handles datasets with a period but without department.
> Add new mf datasets

- src/custom/meteo/views/FormMF.vue
This PR reverses the `!` condition and fixes the case for search with period but without department.
> Fix mf new datasets

- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
Fix https://github.com/ecolabdata/ecospheres/issues/200
> fix(bouquet): missing wording change

- configs/ecospheres/config.yaml
Cf https://github.com/ecolabdata/ecospheres/issues/171#issuecomment-2111934041
> Update robots.txt w/ external sitemap

- src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/237
> feat(bouquet): show draft tag on detail page

- configs/ecospheres/config.yaml
Cf https://github.com/ecolabdata/ecospheres/issues/171#issuecomment-2126590008
> chore: update ecospheres sitemap URL

- src/custom/ecospheres/components/forms/dataset/DatasetCardForSelect.vue
Fix https://github.com/ecolabdata/ecospheres/issues/236
> feat(bouquet): smaller fonts for dataset select card

- src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/204
> fix: bouquet detail title and tag spacing and alignment

- src/views/LoginView.vue
- src/views/LogoutView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/239
> fix: login and logout pages content

- src/custom/ecospheres/components/BouquetSearch.vue
Fix https://github.com/ecolabdata/ecospheres/issues/238
> fix: BouquetSearch themes select wording

- package-lock.json
- package.json
- src/utils/index.js
Fix https://github.com/ecolabdata/ecospheres/issues/244
> fix: upgrade marked and use gfm

- src/custom/ecospheres/components/forms/bouquet/BouquetOwnerForm.vue
Fix https://github.com/ecolabdata/ecospheres/issues/247
> fix(bouquet): select owner by default on form

- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
Related https://github.com/ecolabdata/ecospheres/issues/242
Fix https://github.com/ecolabdata/ecospheres/issues/248
> feat(bouquet): show dataset url under radio button

- src/services/api/DatagouvfrAPI.ts
Hot fix from https://github.com/opendatateam/udata-front-kit/pull/469
> fix: config -> requestConfig

- src/views/NotFoundView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/250
> feat: use 404 from dsfr

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/254
> Update demo universe

- src/services/api/resources/DiscussionsAPI.ts
Fix https://github.com/ecolabdata/ecospheres/issues/265
> fix: authenticate discussion comment API request

- src/custom/ecospheres/components/datasets/DatasetAddToBouquetModal.vue
- src/store/TopicStore.ts
- src/store/UserStore.ts
Fix https://github.com/ecolabdata/ecospheres/issues/277
> fix(bouquet): correct filter for list in DatasetAddToBouquetModal

- package-lock.json
- src/custom/ecospheres/components/BouquetSearch.vue
Fix https://github.com/opendatateam/udata-front-kit/security/dependabot/8
> fix(security): vue-template-compiler and deps

- .github/workflows/create-deploy-release.yml
clone the current branch instead of the default one
> fix create/deploy workflow by cloning the current branch

- package-lock.json
- package.json
- src/components/OrganizationLogo.vue
- src/components/sections/SubSectionDatasets.vue
- src/custom/ecospheres/components/BouquetCard.vue
- src/custom/ecospheres/components/BouquetDatasetCard.vue
- src/custom/ecospheres/components/datasets/DatasetAddToBouquetModal.vue
- src/custom/ecospheres/components/forms/dataset/DatasetCardForSelect.vue
- src/custom/ecospheres/components/forms/dataset/DatasetPropertiesFields.vue
- src/custom/ecospheres/components/forms/dataset/SelectDataset.vue
- src/custom/ecospheres/views/bouquets/BouquetDetailView.vue
- src/custom/meteo-france/views/FormMF.vue
- src/main.ts
- src/model/dataset.ts
- src/model/discussion.ts
- src/model/index.ts
- src/model/resource.ts
- src/model/reuse.ts
- src/model/topic.ts
- src/model/user.ts
- src/services/api/resources/ReusesAPI.ts
- src/store/DatasetStore.ts
- src/store/OrganizationStore.ts
- src/store/ResourceStore.ts
- src/utils/avatar.ts
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
- src/views/organizations/OrganizationDetailView.vue
- src/views/topics/TopicsListView.vue
- migrate to new lib with a lot of new components 🎉 (include previsualisation of data)
@nicolaskempf57 at your return, I would like you to have a global check on this please.
https://669123cd8a2c1ef63abe6805-zrcmyysvds.chromatic.com/?path=/story/components-resource-resource--resource-with-preview
FYI @streino
> migrate: datagouv/components

- configs/ecospheres/config.yaml
Update groupée pour : 
https://github.com/ecolabdata/ecospheres/issues/271
https://github.com/ecolabdata/ecospheres/issues/298
> Update demo env orgs list

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/271
Fix https://github.com/ecolabdata/ecospheres/issues/298
> Update PROD env orgs list

- configs/defis/config.yaml
- src/components/sections/SubSectionTiles.vue
tiny diff in code but without any impact on other products
> config: defis

- src/components/bouquets/BouquetDatasetAccordionTitle.vue
- src/components/bouquets/BouquetDatasetCard.vue
- src/components/bouquets/BouquetDatasetList.vue
- src/model/topic.ts
- src/utils/bouquet.ts
- src/views/bouquets/BouquetDetailView.vue
J'ai ajouté le tag "non disponible" lorsqu'un dataset est archivé.
Il me semble que @martyKN voulait [ajouter un texte supplémentaire.](https://github.com/ecolabdata/ecospheres/issues/276#issuecomment-2236551102)
J'ai réutilisé le code de [`BouquetDatasetCard`](https://github.com/opendatateam/udata-front-kit/blob/5a9ee9c2297a1a4af4ed314e1e8fb65e52511c07/src/components/bouquets/BouquetDatasetCard.vue#L18C1-L43C2) pour pouvoir accéder à `dataset.archived`
Fix https://github.com/ecolabdata/ecospheres/issues/276
> Feat: archived dataset in bouquet shows unavailable tag

- configs/ecospheres/config.yaml
https://github.com/opendatateam/udata-front-kit/pull/508
> chore: update prod config for robots

- doc/a11y/svg.md
New `doc` and `a11y` folders.
Add svg usage recommandations.
> Doc: add svg usage recommandations

- src/store/DatasetStore.ts
Fix https://github.com/opendatateam/udata-front-kit/issues/498
> chore: remove unused DatasetStore.loadMultipleByRef

- configs/defis/config.yaml
- configs/ecospheres/config.yaml
- configs/logistique/config.yaml
- configs/meteo-france/config.yaml
- configs/simplification/config.yaml
- src/services/AuthService.js
- src/services/api/OauthAPI.ts
Nécessite un udata intégrant https://github.com/opendatateam/udata/pull/3138 pour fonctionner.
Fix https://github.com/ecolabdata/ecospheres/issues/315
> chore(oauth): remove clientSecret

- configs/ecospheres/config.yaml
https://github.com/opendatateam/udata-front-kit/pull/514#issuecomment-2383206977
> chore: update oauth client id for prod (no secret)

- public/ecospheres/pages/terms.md
- src/assets/main.css
- src/components/DiscussionsList.vue
- src/components/bouquets/BouquetCard.vue
- src/components/bouquets/BouquetDatasetList.vue
- src/components/bouquets/BouquetList.vue
- src/components/header/HeaderComponent.vue
- src/custom/ecospheres/views/HomeView.vue
- src/views/SimplePageView.vue
- src/views/bouquets/BouquetFormView.vue
- src/views/bouquets/BouquetsListView.vue
J'ai parcouru l'audit RGAA et j'ai corrigé la plupart des petits problèmes de sémantique:
- mauvais niveau de titre
- mauvaise balise (a/button)
- attributs manquants ou incorrects
- etc.
Toutes les issues n'étaient pas encore créées.
Fix https://github.com/ecolabdata/ecospheres/issues/387
Fix https://github.com/ecolabdata/ecospheres/issues/384
Fix https://github.com/ecolabdata/ecospheres/issues/385
Fix https://github.com/ecolabdata/ecospheres/issues/386
> Fix: html semantics and structure

- src/custom/ecospheres/views/HomeView.vue
- src/views/bouquets/BouquetsListView.vue
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
Suppression des placeholders
Ajout/ajustement des labels.
> Fix label and placeholders for search and filter fields

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/404
Related to https://github.com/ecolabdata/ecospheres/issues/357
> Update orgs list

- src/assets/main.css
Update org list on demo following changes on demo only. No need to update prod.
> Release demo 20241014-2

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/391
> Home - nav - Add organizations link

- src/App.vue
- src/assets/main.css
- src/components/bouquets/BouquetList.vue
- src/components/header/HeaderSearch.vue
- src/views/bouquets/BouquetDetailView.vue
- src/views/bouquets/BouquetFormView.vue
- src/views/bouquets/BouquetsListView.vue
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
- src/views/organizations/OrganizationDetailView.vue
Petits ajustements pour compléter la conformité avant la clôture de l'audit d'accessibilité.
Fix https://github.com/ecolabdata/ecospheres/issues/419
Fix https://github.com/ecolabdata/ecospheres/issues/418
Fix https://github.com/ecolabdata/ecospheres/issues/405
> Fix: retours contre audit RGAA

- configs/ecospheres/config.yaml
- public/ecospheres/pages/accessibility.md
- src/assets/main.css
Intitulé du lien dans le footer + contenu de la déclaration suite au contre audit RGAA.
fix
- https://github.com/ecolabdata/ecospheres/issues/437
> feat: update accessibility declaration

- configs/ecospheres/config.yaml
Après mise à jour de l'univers https://github.com/ecolabdata/ecospheres-universe/pull/1#issuecomment-2473886874
> chore: update organizations list on prod

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/483
> chore: update organizations list on demo

- src/model/topic.ts
- src/services/export.ts
Fix : https://github.com/ecolabdata/ecospheres/issues/427
> Fix 404 toast on export with some data missing

- src/App.vue
- src/components/OrganizationCard.vue
- src/components/SearchComponent.vue
- src/components/VIconCustom.vue
- src/components/bouquets/BouquetCard.vue
- src/components/bouquets/BouquetCardHome.vue
- src/components/bouquets/BouquetDatasetAccordionTitle.vue
- src/components/bouquets/BouquetDatasetList.vue
- src/components/bouquets/BouquetDatasetListExport.vue
- src/components/bouquets/BouquetList.vue
- src/components/forms/bouquet/BouquetForm.vue
- src/views/bouquets/BouquetDetailView.vue
- src/views/bouquets/BouquetFormView.vue
- src/views/bouquets/BouquetsListView.vue
- src/views/datasets/DatasetDetailView.vue
- src/views/datasets/DatasetsListView.vue
replace icons with native DSFR elements
> fix: icon cdn DSFR

- src/views/datasets/DatasetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/511
> chore: remove datasets export

- src/components/datasets/ExtendedInformationPanel.vue
- src/components/datasets/ExtendedInformationPanelItem.vue
- src/utils/index.ts
Fix https://github.com/ecolabdata/ecospheres/issues/447
Exemple : https://deploy-preview-632--ecospheres.netlify.app/datasets/658f9d826b47c490ec10d52a
> feat: extra metadata on Dataset

- src/components/bouquets/BouquetCard.vue
conditional render of tags on bouquetCard
fix: https://github.com/ecolabdata/ecospheres/issues/515
> fix: bouquetCard

- src/components/SearchComponent.vue
- src/components/bouquets/BouquetDatasetList.vue
- src/components/bouquets/BouquetGroup.vue
- src/utils/bouquetGroups.ts
- src/utils/index.ts
- src/views/bouquets/BouquetDetailView.vue
logic and markup for factor filtering
fix https://github.com/ecolabdata/ecospheres/issues/440
fix https://github.com/ecolabdata/ecospheres/issues/434
> feat: filtre facteurs

- LICENSE.md
- README.md
- configs/ecospheres/config.yaml
- configs/hackathon/config.yaml
- configs/logistique/config.yaml
- configs/meteo-france/config.yaml
- configs/simplification/config.yaml
- public/ecospheres/pages/about.md
- public/ecospheres/pages/accessibility.md
- public/ecospheres/pages/terms.md
- src/custom/ecospheres/components/HomeFaq.vue
- src/custom/ecospheres/views/HomeView.vue
- src/views/datasets/DatasetsListView.vue
- src/views/organizations/OrganizationsListView.vue
> Manque les virgules en fin de ligne dans la liste de FAQ
J'ai remplacé par des points virgules pour être vraiment conforme 😁 
> Harmoniser le lien explicite à ecologie.gouv.fr dans FAQ
Je n'ai pas compris… @streino c'était ton retour ?
fix https://github.com/ecolabdata/ecospheres/issues/484
fix https://github.com/ecolabdata/ecospheres/issues/517
> fix(homepage): wording and content styles

- configs/ecospheres/config.yaml
Last update of the filters used in the indicator view on ecologie.data.gouv.fr
- updated productor list, levier, thematique, enjeu
- sorted the filters to be able to review the file more easily
> Update Tags for indicators filters

- configs/ecospheres/config.yaml
Avec en prime un formatage du yaml re #673
> chore: enable indicator menu entry

- src/components/OrganizationLogo.vue
- src/components/datasets/ContactPoints.vue
- src/components/datasets/ExtendedInformationPanel.vue
- src/model/contactPoint.ts
- src/model/dataset.ts
- src/services/api/resources/ContactPointAPI.ts
- src/store/ContactPointStore.ts
- src/views/datasets/DatasetDetailView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/536
Exemple : https://deploy-preview-678--ecospheres.netlify.app/datasets/67b42e2a11a9813d380bbd5b/
Pour référence : https://demo.data.gouv.fr/fr/datasets/67b42e2a11a9813d380bbd5b/
> feat(dataset): multi attribution

- configs/defis/config.yaml
- configs/ecospheres/config.yaml
- configs/hackathon/config.yaml
- configs/logistique/config.yaml
- configs/meteo-france/config.yaml
- configs/simplification/config.yaml
- src/components/bouquets/BouquetSearch.vue
- src/model/config.ts
- src/utils/config.ts
- src/views/bouquets/BouquetsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/540
> feat(bouquets): configurable show drafts by default

- src/components/bouquets/BouquetDatasetList.vue
Probablement depuis https://github.com/opendatateam/udata-front-kit/pull/656
> fix(bouquet): search field alignment

- configs/ecospheres/config.yaml
- public/ecospheres/pages/about.md
- src/custom/ecospheres/views/indicators/IndicatorsListView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/544
> chore(ecologie): update wordings

- package-lock.json
- package.json
- src/components/forms/dataset/DatasetEditModal.vue
- src/components/forms/dataset/SelectDataset.vue
- update versions to latest secure while respecting pinned semver https://github.com/opendatateam/udata-front-kit/pull/693/commits/8f78642aaf9621feba71fa355a6aa151c9513949
- force upgrade of vitest (breaking) https://github.com/opendatateam/udata-front-kit/pull/693/commits/cd35e1b2e2ce7b5ae91ac20c5bcad428a81e4488
- remove a warning https://github.com/opendatateam/udata-front-kit/pull/693/commits/be592d01e623209636887fb6793f91bdfe496d0a
> chore: apply security fixes

- .github/workflows/review-app.yml
Follow up from https://github.com/opendatateam/udata-front-kit/pull/712
> fix: no deploy for review app destroy

- src/utils/bouquetGroups.ts
Fix https://github.com/ecolabdata/ecospheres/issues/525
> feat(bouquet): sort factors alphabetically

- configs/logistique/config.yaml
- src/views/datasets/DatasetsListView.vue
> fix(logistique): datasets list

- src/custom/meteo-france/views/FormMF.vue
Same as https://github.com/opendatateam/udata-front-kit/pull/634 but with base `main`
> Button can now unfilter stations, and better wording

- src/views/topics/TopicDetailView.vue
- src/views/topics/TopicFormView.vue
Fix https://github.com/ecolabdata/ecospheres/issues/563
> feat(topic): show clone button for everyone

- configs/meteo-france/config.yaml
> update: config meteo.data.gouv.fr

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/667
> fix(rgaa): add indicator to ecologie site map

- .github/workflows/deploy-review-from-comment.yml
I forgot to `git add` the meat of the work in #802 (because of file renaming) :-/
> fix: add workflow file for comment deploy

- .github/workflows/deploy-review-from-comment.yml
> fix: comment deploy regex

- .github/workflows/create-deploy-release.yml
> ci: fix ci

- package.json
- src/views/topics/TopicDetailView.vue
> chore(lint): no warning allowed

- src/components/header/HeaderComponent.vue
Fix https://github.com/ecolabdata/ecospheres/issues/684
> fix(rgaa): header badge tag

- configs/ecospheres/config.yaml
CF https://github.com/opendatateam/udata-front-kit/pull/822#issuecomment-3149435685
> document editable conf in ecosphere config comments

- configs/meteo-france/config.yaml
Waiting for the next hackathon description
> Change title and remove hackathon page for now

- cypress/support/datagouv_mocks.js
- cypress/support/e2e.js
- cypress/support/generic_mocks.js
Closes https://github.com/opendatateam/udata-front-kit/issues/858
> allow some domains for chrome browser specific requests

- configs/ecospheres/config.yaml
Fix https://github.com/ecolabdata/ecospheres/issues/767
> chore(indicators): remove some filters

- package-lock.json
- package.json
https://github.com/ecolabdata/ecospheres-tabular-dataviz/pull/3
> chore(indicators): upgrade @ecolabdata/tabular-dataviz@1.1.1

- src/components/datasets/ExtendedInformationPanel.vue
Fix https://github.com/ecolabdata/ecospheres/issues/808
> feat(dataset): add publication date
